<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AccountRoutes.fs" />
    <Compile Include="FiscalPeriodRoutes.fs" />
    <Compile Include="Program.fs" />
    <None Include="appsettings.Development.json" />
    <None Include="appsettings.Production.json" />
  </ItemGroup>

  <Target Name="CopyEnvConfig" AfterTargets="Build">
    <Copy SourceFiles="appsettings.Development.json" DestinationFiles="$(OutputPath)appsettings.json" Condition="'$(Configuration)' == 'Debug'" />
    <Copy SourceFiles="appsettings.Production.json" DestinationFiles="$(OutputPath)appsettings.json" Condition="'$(Configuration)' == 'Release'" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\ModelOrchestrator\ModelOrchestrator.fsproj" />
    <ProjectReference Include="..\Model\Model.fsproj" />
  </ItemGroup>

</Project>
