<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Src\ModelOrchestrator\ModelOrchestrator.fsproj" />
    <ProjectReference Include="..\Src\Model\Model.fsproj" />
    <ProjectReference Include="..\Src\Utilities\Utilities.fsproj" />
    <ProjectReference Include="..\Tests\Tests.Integrated\Tests.Integrated.fsproj" />
  </ItemGroup>

</Project>
