<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Tests.Isolated</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NodaTime" Version="3.3.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\ModelOrchestrator\ModelOrchestrator.fsproj" />
    <ProjectReference Include="..\..\Src\Model\Model.fsproj" />
    <ProjectReference Include="..\Tests.Helpers\Tests.Helpers.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Model\Ledger\AccountComponent.fs" />
    <Compile Include="Model\Ledger\FiscalPeriod.fs" />
    <Compile Include="Model\Ledger\JournalEntryComponent.fs" />
    <Compile Include="Model\Ledger\JournalEntryExternalReference.fs" />
    <Compile Include="Model\Money.fs" />
    <Compile Include="Model\DataIngestion\StageEntryStatusTransition.fs" />
    <Compile Include="Model\DataIngestion\Classifier.fs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
