<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Tests.Integrated</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NodaTime" Version="3.3.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\Model\Model.fsproj" />
    <ProjectReference Include="..\..\Src\SonOfLeoCli\SonOfLeoCli.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="_Cleanup.fs" />
    <Compile Include="GenericTestProperties.fs" />
    <Compile Include="Model\Ledger\Account.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="SonOfLeoCli\CliExecutor.fs" />
    <Compile Include="SonOfLeoCli\Program.fs" />
  </ItemGroup>

  <Target Name="CopyEnvConfig" AfterTargets="Build">
    <Copy SourceFiles="appsettings.Development.json" DestinationFiles="$(OutputPath)appsettings.json" />
  </Target>

</Project>
