<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Json.fs" />
    <Compile Include="CommandRoute.fs" />
    <Compile Include="InterfaceContracts\SharedContracts.fs" />
    <Compile Include="InterfaceContracts\AccountContracts.fs" />
    <Compile Include="InterfaceContracts\FiscalPeriodContracts.fs" />
    <Compile Include="InterfaceContracts\JournalContracts.fs" />
    <Compile Include="InterfaceContracts\ReportsContracts.fs" />
    <Compile Include="BoundaryConverters\AccountFieldConverters.fs" />
    <Compile Include="BoundaryConverters\JournalEntryFieldConverters.fs" />
    <Compile Include="BoundaryConverters\MoneyFieldConverters.fs" />
    <Compile Include="BoundaryConverters\OrchestrationConverters.fs" />
    <Compile Include="BoundaryConverters\FiscalPeriodFieldConverters.fs" />
    <Compile Include="BoundaryConverters\ReportConverters.fs" />
    <Compile Include="Routes\AccountRoutes.fs" />
    <Compile Include="Routes\FiscalPeriodRoutes.fs" />
    <Compile Include="Routes\JournalEntryRoutes.fs" />
    <Compile Include="ReportVisualizationAssets\HtmlWrapper.fs" />
    <Compile Include="ReportWriters\TrialBalanceWriter.fs" />
    <Compile Include="Routes\ReportRoutes.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Context\Context.fsproj" />
    <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.fsproj" />
    <ProjectReference Include="..\ModelOrchestrator\ModelOrchestrator.fsproj" />
    <ProjectReference Include="..\Model\Model.fsproj" />
    <ProjectReference Include="..\Utilities\Utilities.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.3.3" />
  </ItemGroup>

</Project>
